# Generated by Django 4.1.7 on 2023-04-27 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_conductores_bus_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductores',
            name='fechaNacimiento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
