# Generated by Django 4.1.7 on 2023-04-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_conductores_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductores',
            name='edad',
        ),
        migrations.AlterField(
            model_name='conductores',
            name='fechaNacimiento',
            field=models.DateField(auto_created=True),
        ),
    ]
