# Generated by Django 4.1.7 on 2023-05-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_cronograma_infracciones_conductores_alerta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='geocercas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=150)),
                ('siguiente_geocerca', models.CharField(max_length=150)),
                ('anterior_geocerca', models.CharField(max_length=150)),
                ('tiempo_v', models.CharField(max_length=150)),
            ],
        ),
    ]
