# Generated by Django 4.1.7 on 2023-06-01 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_geocercas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracciones',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='infracciones',
            name='conductor_infractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.conductores'),
        ),
        migrations.AddField(
            model_name='infracciones',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.rutas'),
        ),
        migrations.AddField(
            model_name='infracciones',
            name='minutos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.geocercas'),
        ),
    ]
