# Generated by Django 4.1.7 on 2023-06-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_remove_infracciones_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracciones',
            name='minutos',
            field=models.IntegerField(null=True),
        ),
    ]
