# Generated by Django 4.1.7 on 2023-06-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0009_rename_conductor_infractor_infracciones_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.CharField(max_length=6)),
                ('hora_fin', models.CharField(max_length=6)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.rutas')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.vehiculos')),
            ],
        ),
    ]
