# Generated by Django 4.1.7 on 2023-06-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0010_reporteprogramacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutas',
            old_name='numero_interno',
            new_name='bus_asignado',
        ),
        migrations.RenameField(
            model_name='vehiculos',
            old_name='numero_interno',
            new_name='bus_asignado',
        ),
        migrations.AlterField(
            model_name='conductores',
            name='bus_asignado',
            field=models.CharField(max_length=4),
        ),
    ]
