# Generated by Django 4.1.7 on 2023-06-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0012_rename_bus_asignado_rutas_numero_interno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporteGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.cronograma')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.conductores')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.rutas')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.vehiculos')),
            ],
        ),
    ]
