# Generated by Django 4.1.7 on 2023-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0013_reportegeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='fechaNacimiento',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
