# Generated by Django 4.1.7 on 2023-06-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0014_alter_conductores_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='nombre_completo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
