# Generated by Django 4.1.7 on 2023-06-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0018_alter_conductores_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='documento',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
