# Generated by Django 4.1.7 on 2023-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0019_alter_conductores_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='cronograma',
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='numero_interno',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='placa',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='tipo',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
