# Generated by Django 4.1.7 on 2023-06-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0020_remove_vehiculos_cronograma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportegeneral',
            name='cronograma',
        ),
        migrations.RemoveField(
            model_name='reportegeneral',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='reportegeneral',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='bus_asignado',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='nombre_completo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='placa_bus_asignado',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='ruta_asignada',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='tabla_asignada',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='tipo_bus_asignado',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='viajes_programados',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='reportegeneral',
            name='documento',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
